### ISSUE TITLE
History search (reverse-i-search)

### ISSUE THREAD

**Issue by nik9000** [tinkerpop/gremlin#386]
It'd be nice to have readline's ```history-search-backward``` in the rexster and gremlin shells.  It looks like jline2 supports this but ctrl-r doesn't do anything for me on the console.

**Comment by spmallette** [comment]
we can't/won't bump the jline version for TP2 so in that sense we can't really support this.  However, i tested in `gremlin.sh` for TP3 and `ctrl-r` works nicely. thanks for pointing that one out to me - didn't know that such a useful feature was just hanging around there :)
