### ISSUE TITLE
Gremlin g.V('label','foo') query fails with incorrect type casts

### ISSUE THREAD

**Issue by szetheli** [tinkerpop/gremlin#390]
Vertex 'label' searches don't work in Gremlin.

Repro:
Download and install the 0.5.4 titan product.  (w/ gremlin 2.5.0 jars)
Start a titan cassandra instance
console>bin/gremlin.sh
gremlin> g = TitanFactory.open("cassandra:localhost")
gremlin> mgmt = g.getManagementSystem()
gremlin> mgmt.makeVertexLabel('Segment').make()
gremlin> mgmt.commit()
gremlin> g.newTransaction()
gremlin> g.addVertexWithLabel('Segment')
gremlin> g.commit()
gremlin> g.V('label','Segment')

Actual:
15:00:08 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
com.thinkaurelius.titan.graphdb.vertices.CacheVertex cannot be cast to com.tinkerpop.blueprints.Edge
Display stack trace? [yN] y
java.lang.ClassCastException: com.thinkaurelius.titan.graphdb.vertices.CacheVertex cannot be cast to com.tinkerpop.blueprints.Edge
	at com.tinkerpop.pipes.filter.LabelFilterPipe.processNextStart(LabelFilterPipe.java:25)
	at com.tinkerpop.pipes.filter.LabelFilterPipe.processNextStart(LabelFilterPipe.java:13)
	at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
	at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
	at com.tinkerpop.pipes.transform.ToStringPipe.processNextStart(ToStringPipe.java:24)
	at com.tinkerpop.pipes.transform.ToStringPipe.processNextStart(ToStringPipe.java:16)
	at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
	at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.ResultHookClosure.call(ResultHookClosure.java:81)
	at groovy.lang.Closure.call(Closure.java:428)

Expected:
List of the vertex that was created above.

Cause:
com.tinkerpop.gremlin.java.GremlinPipeline.has(String, Predicate, Object) is doing a string match on 'label' in order to decide to create the LabelFilterPipeline, but LabelFilterPipeline is expecting to be working on Edge not Vertex.  Since this instance of 'label' is being applied to a Vertex label, that behavior is incorrect.

The buggy code is the same in the master:
https://github.com/tinkerpop/gremlin/blob/master/gremlin-java/src/main/java/com/tinkerpop/gremlin/java/GremlinPipeline.java (line 219)
https://github.com/tinkerpop/pipes/blob/master/src/main/java/com/tinkerpop/pipes/filter/LabelFilterPipe.java (line 25)

**Comment by jbmusso** [comment]
TinkerPop 2.x doesn't have the concept of vertex labels, only edge labels - this is why you're seeing this error. Vertex labels will be added in TinkerPop3, which Titan v0.9.0+ will support. See the TinkerPop3 documentation for more information on the `.hasLabel()` step: http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#has-step

If you wish to retrieve vertices by label when using Titan v0.5.x+, you'll have to skip the Gremlin API and issue a direct query to the graph, then convert it back to a Gremlin pipeline with the identity step ._():
```groovy
g.query().has('label', 'Segment').vertices()._()
```
Note that querying vertices by label in Titan doesn't hit indexes, so performance will be a concern.

**Comment by Airswoop1** [comment]
I'm on 0.5.3 and able to create vertex's with labels with
g.addVertexWithLabel('user'). Unfortunately we found out (as you note) that
they cannot be used in queries. We just use a universal Property Key called
vertex_type, create an index for it and just use that.

**Comment by okram** [comment]
Vertex labels are in TP3 and Titan 0.9+ supports them.
