### ISSUE TITLE
Current releases are stable to be used? 

### ISSUE THREAD

**Issue by danyaljj** [tinkerpop/gremlin#391]
I am new to gremlin; sorry if I am asking an obvious question. 

I was checking your maven repository: 
http://mvnrepository.com/artifact/com.tinkerpop/gremlin-core
and I realized that the latest versions are Milestones (M). Are these versions ready to be used for serious large-scaled projects? 

Also, the usage counts are very small. How accurate is this number? 
http://mvnrepository.com/artifact/com.tinkerpop
Like `hadoop-gremlin ` has 0 count, and `neo4j-gremlin ` has ` 1 count.

**Comment by spmallette** [comment]
You aren't looking in the right place.  TinkerPop3 is now a project of the Apache Foundation:

https://github.com/apache/incubator-tinkerpop

Latest information is here:

http://tinkerpop.incubator.apache.org/

Maven info here:

http://mvnrepository.com/artifact/org.apache.tinkerpop
