### ISSUE TITLE
Console Exceptions and Arguments

### ISSUE THREAD

**Issue by dstuebe** [tinkerpop/gremlin#393]
I using gremlin console and had trouble debugging my script because a File Not Found exception in my script was being caught here:
https://github.com/tinkerpop/gremlin/blob/master/gremlin-groovy/src/main/java/com/tinkerpop/gremlin/groovy/console/Console.java#L91-L93

Would it be appropriate to put a separate try catch block around the execution of the lines - ideally returning line number etc?

**Comment by spmallette** [comment]
Hi @dstuebe - I don't believe you will see any more releases of Gremlin 2.x.  Please see all our fresh new development on Apache TinkerPop 3.x: http://tinkerpop.apache.org/

If you need that patched it is best you manged it yourself at this point i think.  Thanks.

**Comment by dstuebe** [comment]
Well - same issue still applies in TP3
https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy#L290

Sorry I was sloppy and did not check where I was opening the issue.

The following code:
```groovy
println 'here'
s = new File('foobarbaz').text
println 'not here'
```
Will produce:
```
$ bin/gremlin.sh scripts/io_error.groovy
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: aurelius.titan
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.tinkergraph
here
==>null
Gremlin initialization file not found at [scripts/io_error.groovy].
$
```

When the file foobarbaz does not exist.

This is very misleading as it appears that the error is in reading the script not the script itself.

Not setup to report issues on the new Jira project - would you care to report this for me @spmallette ?

**Comment by spmallette** [comment]
Thanks for reporting this.....

https://issues.apache.org/jira/browse/TINKERPOP-1055
